// The coin economy: what everything is worth, what the wandering merchant will
// part with, and the two transactions.
//
// Price scale
// -----------
// One coin is one shovelful of dirt. Everything else is quoted against that:
//
//     dirt / cobblestone      1        a bucket              ~37
//     stick / seeds           1-2      astral crystal         60
//     coal                    4        sunstone               30
//     hide / wheat            3-5      iron block            108
//     iron ingot             12        an astral tool     62-183
//     gold ingot             25        crystal block         540
//
// Nothing in that table is typed in twice. A value comes from the first of
// these that applies:
//
//   1. an explicit override, for the raw materials that have no properties to
//      reason from — an ingot is not hard, not nutritious and not fuel, so
//      there is nothing to derive its worth from but a decision;
//   2. the cheapest recipe or smelt that produces it, priced at the value of
//      its inputs plus a little labour;
//   3. a formula over what the item already declares — block hardness and tool
//      tier, food value, fuel value, stack size.
//
// Recipes deliberately *override* the formula rather than raising it. Taking
// the maximum is what a crafting exploit looks like: a torch's intrinsic value
// is high because it emits light, so four torches would have sold for six times
// the coal they were made from. Priced at their inputs, no amount of crafting
// mints coins, and the merchant's 3.2x spread (see below) is the only margin
// in the game.
//
// The point of deriving rather than tabulating is that the item registry keeps
// growing. Anything new that declares `food`, or is craftable from things that
// already have a price, gets a sensible one without being listed here.

import { ITEMS, N_ITEMS, itemIdOf } from './Items.js';
import { BLOCKS } from '../world/Blocks.js';
import { RECIPES, SMELTING, recipeCost } from './Recipes.js';

/** The merchant pays this fraction of an item's value. */
const SELL_RATE = 0.5;
/** And charges this multiple of it. The 3.2x spread is the whole margin. */
const BUY_RATE = 1.6;
/** Coins a crafting step adds on top of its inputs. */
const CRAFT_LABOUR = 0.5;
/** A smelt costs fuel as well as time, so it adds rather more. */
const SMELT_MARKUP = 1.1;
const SMELT_LABOUR = 1.2;

/**
 * Raw materials, priced by decision. These are the anchors the derivation
 * hangs off — change one and everything made from it moves with it.
 */
const OVERRIDE = {
  coin: 1,
  stick: 1,
  seeds: 2,
  feather: 2,
  flint: 3,
  wheat: 3,
  coal: 4,
  charcoal: 4,
  hide: 5,
  raw_iron: 8,
  raw_gold: 16,
  // Smelted metal is worth more than the raw lump on purpose: the kiln has to
  // pay for itself. These also break the one price cycle in the registry —
  // nine ingots make a block and a block makes nine ingots — by settling the
  // ingot before the block is ever asked about.
  iron_ingot: 12,
  gold_ingot: 25,
  crystal: 60,
  // The rest of the metal ladder, anchored between the two that were already
  // here: copper sits below iron, silver between iron and gold. Same reason as
  // above — a raw lump and a bar have no properties to reason from, and the
  // nine-to-one storage blocks would form a price cycle without them.
  raw_copper: 5,
  copper_ingot: 8,
  raw_silver: 12,
  silver_ingot: 18,
  // Sulfur is common, shallow and only good for one recipe, so it is priced
  // level with coal rather than as a mineral.
  sulfur: 4,
  // Gems drop straight out of the ore with no smelt to pay for, so their value
  // has to carry the whole cost of the depth they sit at. Amethyst is a tier-2
  // find; the three tier-3 gems sit either side of astral crystal; a void shard
  // needs an astral pick to touch at all and is the deepest thing on the planet.
  amethyst: 22,
  emerald: 34,
  ruby: 46,
  sapphire: 46,
  void_shard: 95,
  // Above a void shard, which is the deepest thing you can dig for, because a
  // cinder cannot be dug for at all — it is paid for in nights survived. The
  // merchant will buy them; he will never sell one.
  cinder: 120,
  // Sunstone is generated by nothing and crafted from nothing: the merchant is
  // the only source on the planet, so it is priced as the luxury it is.
  glowstone: 30,
  // The bucket's own recipe (three iron) already values it; the filled one has
  // no recipe at all and would otherwise fall through to the stack-size guess.
  water_bucket: 38,
};

// --- the formula ------------------------------------------------------------

/**
 * A block's worth from how hard it is to get out of the ground. Tier dominates
 * — needing a better pickaxe is the real gate — and hardness only separates
 * blocks within a tier. Light and fuel are small bonuses for utility.
 */
function blockValue(b) {
  return 0.6 + b.hardness * 0.35 + b.tier * 3 + b.light * 0.4 + b.fuel * 0.3;
}

/**
 * Fallback for a tool with no recipe. Every tool in the game has one, so this
 * only ever runs for something added later; tier is squared because each rung
 * of the tool ladder costs disproportionately more to reach.
 */
function toolValue(t) {
  return t.tier * t.tier * 4 + t.durability * 0.06;
}

/**
 * Food, from nutrition. This is the branch that has to hold up for items this
 * file has never heard of, so it reads only what every food declares: how much
 * it restores, whether it has been through a fire, and how deep it stacks —
 * anything that stacks shallowly is scarce by the registry's own admission.
 */
function foodValue(def) {
  const stack = def.stack ?? 64;
  return 1.1 * def.food + (def.cooked ? 2 : 0) + (stack <= 16 ? 4 : 0);
}

function intrinsic(def) {
  if (def.tool) return toolValue(def.tool);
  if (def.block !== undefined) return blockValue(BLOCKS[def.block]);
  if (def.food) return foodValue(def);
  if (def.fuel) return 1 + def.fuel * 0.5;
  // Nothing to go on but how many fit in a slot. A stack of one is a tool, a
  // pail or a keepsake; a stack of 999 is small change.
  return 160 / ((def.stack ?? 64) + 7);
}

// --- derivation -------------------------------------------------------------

const _value = new Float64Array(N_ITEMS);
const _done = new Uint8Array(N_ITEMS);
const _busy = new Uint8Array(N_ITEMS);

/** Unrounded value, memoised. */
function raw(id) {
  const def = ITEMS[id];
  if (!def) return 0;
  if (_done[id]) return _value[id];

  const ov = OVERRIDE[def.name];
  if (ov !== undefined) { _value[id] = ov; _done[id] = 1; return ov; }

  const base = intrinsic(def);
  // A recipe that leads back to this item cannot help price it. Hand back the
  // formula and do NOT memoise: the outer call is still mid-flight and will
  // write the real answer.
  if (_busy[id]) return base;
  _busy[id] = 1;

  let best = Infinity;
  for (const r of RECIPES) {
    if (r.out !== id) continue;
    let sum = CRAFT_LABOUR;
    for (const c of recipeCost(r)) sum += c.count * raw(c.item);
    best = Math.min(best, sum / r.count);
  }
  for (const s of SMELTING) {
    if (s.out !== id) continue;
    best = Math.min(best, (raw(s.in) * SMELT_MARKUP + SMELT_LABOUR) / s.count);
  }

  _busy[id] = 0;
  const v = best === Infinity ? base : best;
  _value[id] = v; _done[id] = 1;
  return v;
}

/** Base worth of one item, in whole coins. Never below 1. */
export function valueOf(itemId) {
  return Math.max(1, Math.round(raw(itemId)));
}

/** What the merchant pays for one. It buys everything. */
export function sellPriceOf(itemId) {
  return Math.max(1, Math.round(valueOf(itemId) * SELL_RATE));
}

/** What the merchant charges for one, if it stocks it at all. */
export function buyPriceOf(itemId) {
  return Math.max(2, Math.round(valueOf(itemId) * BUY_RATE));
}

// --- what the merchant carries ----------------------------------------------

/**
 * The allow-list, with the quantity band each line is stocked in.
 *
 * The rule behind it: a merchant sells convenience and scarcity, never
 * substitutes for mining. So no ores, no crystal, no metal, no tool above
 * wood, and nothing you can knock out of the ground in front of you. What is
 * here is either a shortcut past a chore (seeds, saplings, torches, a pail),
 * something that only grows somewhere else (cactus, pumpkin, glowcaps), or —
 * in sunstone's case — the one block on the planet with no other source.
 */
const WARES = [
  ['seeds', 6, 16],
  ['sapling', 2, 6],
  ['wheat', 4, 10],
  ['stick', 8, 20],
  ['coal', 3, 8],
  ['flint', 2, 6],
  ['clay', 4, 12],
  ['hide', 2, 5],
  ['feather', 3, 9],
  ['torch', 6, 16],
  ['bucket', 1, 1],
  ['lantern', 1, 2],
  ['glowstone', 1, 3],
  ['mushroom', 1, 4],
  ['cactus', 1, 4],
  ['pumpkin', 1, 3],
  ['moss_stone', 3, 8],
  ['ice', 2, 6],
  ['wood_pick', 1, 1],
  ['wood_axe', 1, 1],
  ['wood_shovel', 1, 1],
  // Hide armour only, and by the same rule as the wooden tools: the bottom rung
  // is a shortcut past a chore, every rung above it is the reward for mining.
  // A trader who sold iron plate would make the forge decorative.
  ['hide_helm', 1, 1],
  ['hide_chest', 1, 1],
  ['hide_legs', 1, 1],
  ['hide_boots', 1, 1],
];

const WARE_IDS = new Set(WARES.map(([n]) => itemIdOf(n)).filter(Boolean));

const COIN = itemIdOf('coin');

/**
 * Will the merchant sell this?
 *
 * Food is admitted by its property rather than by name on purpose. The pantry
 * grows; a trader who only knew about bread would look emptier every patch.
 */
export function canBuy(itemId) {
  if (!itemId || itemId === COIN) return false;
  if (WARE_IDS.has(itemId)) return true;
  const def = ITEMS[itemId];
  return !!(def && def.food && !def.tool);
}

/** Will the merchant take this off you? Everything but its own coins. */
export function canSell(itemId) {
  return !!itemId && itemId !== COIN;
}

/** The curated lines — the goods this trader exists to carry. */
function warePool() {
  const pool = [];
  for (const [name, lo, hi] of WARES) {
    const id = itemIdOf(name);
    if (id) pool.push([id, lo, hi]);
  }
  return pool;
}

/**
 * Everything else edible, admitted by property rather than by name so the
 * pantry can grow without this file being edited.
 *
 * It has to be drawn separately, and sparingly. When the larder was six items
 * a uniform draw over both lists was fine; it is thirty now, and measured over
 * 3,196 rolled lines it had taken 55% of every pack. A merchant carrying six
 * dinners and a torch is not the trader the rest of this file describes.
 */
function larderPool() {
  const pool = [];
  for (let id = 1; id < N_ITEMS; id++) {
    const def = ITEMS[id];
    if (!def || WARE_IDS.has(id) || !def.food || def.tool) continue;
    // Rich food in smaller lots, so a merchant is never a canteen.
    pool.push([id, 1, def.food >= 8 ? 3 : 5]);
  }
  return pool;
}

/** Shuffle in place; drawing with `splice` is the same thing but quadratic. */
function shuffle(a, rng) {
  for (let i = a.length - 1; i > 0; i--) {
    const j = (rng() * (i + 1)) | 0;
    const t = a[i]; a[i] = a[j]; a[j] = t;
  }
  return a;
}

/** How many distinct lines one merchant carries. */
const LINES_MIN = 6;
const LINES_MAX = 10;
/** And how many of those may be dinner. */
const FOOD_LINES_MIN = 1;
const FOOD_LINES_MAX = 3;

/**
 * A pack, not a shop. Each merchant draws a handful of lines in limited
 * quantities, so the answer to "can I buy forty torches" is no, and the next
 * one along will be carrying something else.
 *
 * @param {() => number} rng
 * @returns {Array<{item:number, count:number}>}
 */
export function rollStock(rng = Math.random) {
  const lines = LINES_MIN + Math.floor(rng() * (LINES_MAX - LINES_MIN + 1));
  // A meal or two, never a menu. The rest of the pack is the curated list.
  const food = FOOD_LINES_MIN + Math.floor(rng() * (FOOD_LINES_MAX - FOOD_LINES_MIN + 1));
  const picked = [
    ...shuffle(larderPool(), rng).slice(0, food),
    ...shuffle(warePool(), rng).slice(0, Math.max(0, lines - food)),
  ];
  return shuffle(picked, rng).map(([item, lo, hi]) => ({
    item,
    count: lo + Math.floor(rng() * (hi - lo + 1)),
  }));
}

// --- requests ---------------------------------------------------------------

/**
 * What a trader might ask you to bring him.
 *
 * The planet is full of systems and none of them ask the player for anything —
 * you can mine, farm, cook, forge and build without the world ever expressing
 * a preference. A standing request is the smallest thing that gives a session
 * a shape: something specific to go and get, and a reason to prefer one of the
 * dozen things you could be doing.
 *
 * Deliberately drawn from what you *make* or *dig*, never from what he sells —
 * being asked to fetch the torches he is holding would be a joke at the
 * player's expense.
 */
const REQUESTS = [
  ['iron_ingot', 5, 12],
  ['copper_ingot', 6, 14],
  ['silver_ingot', 4, 10],
  ['gold_ingot', 3, 8],
  ['crystal', 2, 5],
  ['amethyst', 3, 7],
  ['emerald', 2, 5],
  ['ruby', 2, 4],
  ['sapphire', 2, 4],
  ['cinder', 1, 3],
  ['bread', 4, 9],
  ['cooked_meat', 4, 10],
  ['hide', 8, 16],
  ['feather', 8, 16],
  ['charcoal', 6, 14],
  ['stone_brick', 12, 24],
  ['glass', 8, 16],
  ['planks', 16, 32],
];

/**
 * What he pays over the odds for it. High enough that filling a request beats
 * selling the same goods across the counter, or there would be no reason to
 * take one.
 */
const REQUEST_BONUS = 2.6;

/**
 * Roll one standing request, or null for a trader who wants nothing.
 *
 * Anything he stocks is filtered out here rather than trimmed from the list
 * above, because `canBuy` admits every food by property: bread and cooked meat
 * read as fine entries and were being asked for by a man with a bag of
 * sandwiches. Asking the question keeps the two in step if either list moves.
 */
export function rollRequest(rng = Math.random) {
  if (rng() < 0.18) return null;
  const pool = REQUESTS.filter(([name]) => {
    const id = itemIdOf(name);
    return id && !canBuy(id);
  });
  if (!pool.length) return null;
  const [name, lo, hi] = pool[(rng() * pool.length) | 0];
  const item = itemIdOf(name);
  const count = lo + Math.floor(rng() * (hi - lo + 1));
  return { item, count, reward: Math.max(4, Math.round(sellPriceOf(item) * count * REQUEST_BONUS)) };
}

/**
 * Hand over the goods. All or nothing: a half-filled request would need its own
 * progress state on a trader who walks away in seven minutes.
 *
 * @returns {boolean} whether it was filled
 */
export function fulfilRequest(inventory, request, purse) {
  if (!request || request.done) return false;
  if (inventory.count(request.item) < request.count) return false;
  // He pays from his own purse like any other trade, and a request he cannot
  // cover is one he should not have asked for — but if his float has run dry
  // since, honour it anyway rather than eating the goods.
  const taken = inventory.remove(request.item, request.count);
  if (taken < request.count) {
    inventory.add(request.item, taken);
    return false;
  }
  if (purse) purse.coins = Math.max(0, purse.coins - Math.min(purse.coins, request.reward));
  inventory.add(COIN, request.reward);
  request.done = true;
  return true;
}

// --- transactions -----------------------------------------------------------

/** Coins on hand. */
export function coinsOf(inventory) {
  return inventory.count(COIN);
}

/**
 * Buy up to `want` of an item. Stops on the first thing that runs out — stock,
 * coins or slots — and reports what actually happened, so the caller never has
 * to pre-check any of them.
 *
 * @returns {number} how many changed hands
 */
export function buyFrom(inventory, stock, itemId, want = 1) {
  if (!canBuy(itemId)) return 0;
  const line = stock?.find((s) => s.item === itemId);
  if (!line) return 0;
  const price = buyPriceOf(itemId);
  let n = 0;
  while (n < want) {
    if (line.count <= 0) break;
    if (coinsOf(inventory) < price) break;
    if (!inventory.hasRoom(itemId)) break;
    inventory.remove(COIN, price);
    inventory.add(itemId, 1);
    line.count--;
    n++;
  }
  if (n) inventory.changed();
  return n;
}

/**
 * Sell up to `want` of an item. Wear is ignored: a worn tool fetches the same
 * as a fresh one. That is deliberate rather than an oversight — the merchant
 * stocks no tool above wood, so there is no loop to close by buying cheap and
 * selling used.
 *
 * @returns {number} how many were sold
 */
export function sellTo(inventory, itemId, want = 1, purse = null) {
  if (!canSell(itemId)) return 0;
  const price = sellPriceOf(itemId);
  let n = 0;
  while (n < want) {
    if (inventory.count(itemId) <= 0) break;
    if (!inventory.hasRoom(COIN)) break;
    // A trader carries a float, not a treasury. Without one, every renewable
    // block in the world is a coin printer: cobblestone regrows as fast as you
    // can swing, and cutting it into slabs first doubled the rate because two
    // half-blocks each round up to the one-coin minimum. Capping what the
    // merchant can pay makes the question "what is worth selling to *this*
    // one" rather than "how long can I stand here".
    if (purse && purse.coins < price) break;
    if (inventory.remove(itemId, 1) < 1) break;
    if (purse) purse.coins -= price;
    inventory.add(COIN, price);
    n++;
  }
  if (n) inventory.changed();
  return n;
}

export { COIN as COIN_ITEM };
